name: Build and Test
run-name: ${{ github.workflow }} (${{ github.head_ref || github.ref_name }})
on:
  push:
    # Run for all branches excluding dependabot branches. Do NOT run for tags.
    branches-ignore:
      - "dependabot/**"

env:
  PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}
  projects:


jobs:
  type-check:
