name: Build, Test and Publish Package

on:
  workflow_call:
    inputs:
      vault_version:
        description: Vault version
        type: string
      path:
        description: 'Path to package.json'
        required: true
        type: string
      bump:
        description: |-
          How to bump the package version:
          - `none` - do not bump version and do not publish
          - `patch` - bump patch version
          - `minor` - bump minor version
          - `major` - bump major version
        required: false
        default: none
        type: string
    secrets:
      CICD_RELEASES_PAT:
        description: 'Personal Access Token for pushing changes to repository'
        required: true
      PVAULT_SERVICE_LICENSE:
        description: 'Vault license for testing'
        required: true
      NPM_REGISTRY_TOKEN:
        description: 'Token for NPM registry'
        required: true

# Necessary for AWS assume role.
permissions:
  id-token: write
  contents: read

jobs:
  build-test-publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # By default, the ref is the commit hash that triggered the original workflow.
          # Meaning it is missing changes that are committed by the workflow itself.
          # Explicitly set ref to the branch name, so we pull the latest changes committed by the CI.
          ref: ${{ github.ref_name }}
          token: ${{ secrets.CICD_RELEASES_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: ${{ inputs.path }}/yarn.lock

      - name: Bump version
        id: bump
        if: inputs.bump != 'none'
        run: |
          yarn --cwd ${{ inputs.path }} version \
            --no-git-tag-version \
            --no-commit-hooks \
            --${{ inputs.bump }}
          
          echo "package_name=$(jq -r '.name' ${{ inputs.path }}/package.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r '.version' ${{ inputs.path }}/package.json)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: yarn --cwd ${{ inputs.path }} --frozen-lockfile

      - name: Bump @piiano dependencies
        run: yarn --cwd ${{ inputs.path }} upgrade --scope @piiano

      - name: Run build
        run: yarn --cwd ${{ inputs.path }} build
        env:
          VAULT_VERSION: ${{ inputs.vault_version }}

      - name: Run tests
        run: yarn --cwd ${{ inputs.path }} test
        env:
          VAULT_VERSION: ${{ inputs.vault_version }}
          PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}

      - name: Configure aws credentials
        if: inputs.bump != 'none' && github.ref_name == 'main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::202832695688:role/vault-saas-prod-piiano-vault-typescript-github-actions
          aws-region: us-east-2

      - name: Configure NPM credentials
        if: inputs.bump != 'none' && github.ref_name == 'main'
        run: |
          cat <<EOF >.npmrc
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_REGISTRY_TOKEN }}
          EOF

      - name: Publish package
        if: inputs.bump != 'none' && github.ref_name == 'main'
        run: yarn --cwd ${{ inputs.path }} push

      - name: Commit changes
        if: inputs.bump != 'none' && github.ref_name == 'main'
        run: |
          git config --global user.email "cicd@piiano.com"
          git config --global user.name "Github Actions"
          git add ${{ inputs.path }}/yarn.lock ${{ inputs.path }}/package.json
          git status
          git commit -m "chore: bump ${{ steps.bump.outputs.package_name }} to ${{ steps.bump.outputs.version }}"
          git push
