name: Publish
run-name: ${{ github.workflow }} (${{ github.head_ref || github.ref_name }})

on:
  push:
    branches-ignore:
      - dependabot/**
  workflow_dispatch:
    inputs:
      vault_version:
        description: Vault version
        required: true
        type: string
      bump-testcontainers-vault:
        description: Bump `@piiano/testcontainers-vault` version
        required: false
        default: none
        type: choice
        options: [none, patch, minor, major]
      bump-vault-client:
        description: Bump `@piiano/vault-client` version
        required: false
        default: patch
        type: choice
        options: [none, patch, minor, major]
      bump-typeorm-encryption:
        description: Bump `@piiano/typeorm-encryption` version
        required: false
        default: patch
        type: choice
        options: [none, patch, minor, major]

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CICD_RELEASES_PAT }}

      - name: Update README to reference Vault version ${{ inputs.vault_version }}
        env:
          LINE: This package is compatible with Vault version
        run: |
          sed -i -E \
            "s|$LINE [0-9]+\.[0-9]+\.[0-9]+|$LINE ${{ inputs.vault_version }}|g" \
            $(git ls-files README.md '**/README.md')

      - name: Commit and push changes
        # even though we're using `if: github.event_name == 'workflow_dispatch'` in the job definition
        # we still want to be extra safe and make sure we don't push changes to workflow that is triggered by push event.
        if: github.event_name != 'push'
        run: |
          git config --global user.email "cicd@piiano.com"
          git config --global user.name "Github Actions"
          git add README.md '**/README.md'
          git status
          git commit -a -m 'Update README.md files with to Vault version ${{ inputs.vault_version }}'
          git push

  build-test-publish:
    needs:
      - update-readme
    if: always() && (needs.update-readme.result == 'success' || needs.update-readme.result == 'skipped')
    name: "@piiano/${{ matrix.package }}"
    uses: ./.github/workflows/build-test-publish-package.yml
    strategy:
      matrix:
        package:
          - testcontainers-vault
          - vault-client
          - typeorm-encryption
      # we need to run jobs sequentially because of the way packages depend on each other
      max-parallel: 1
      fail-fast: true
    with:
      path: ./sdk/${{ matrix.package }}
      # When bumping version the called workflow will perform a commit and push.
      # When github.event_name == 'push' we set bump to 'none' to prevent creating another commit and push that would cause an infinite loop.
      bump: >-
        ${{ 
          github.event_name == 'push' &&
          'none' ||
          inputs[format('bump-{0}', matrix.package)]
        }}
    secrets: inherit
