name: Build, Test and Publish
run-name: ${{ github.workflow }} (${{ github.head_ref || github.ref_name }})

on:
  push:
    branches-ignore:
      - dependabot/**
  workflow_dispatch:
    inputs:
      vault-version:
        description: Vault version
        required: true
      bump-testcontainers-vault:
        description: Bump `@piiano/testcontainers-vault` version
        required: false
        default: none
        type: choice
        options: [none, patch, minor, major]
      bump-vault-client:
        description: Bump `@piiano/vault-client` version
        required: false
        default: patch
        type: choice
        options: [none, patch, minor, major]
      bump-typeorm-encryption:
        description: Bump `@piiano/typeorm-encryption` version
        required: false
        default: patch
        type: choice
        options: [none, patch, minor, major]

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
#    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Update README to reference Vault version ${{ inputs.vault-version }}
        env:
          LINE: This package is compatible with Vault version
        run: |
          sed -i -E \
            "s|$LINE [0-9]+\.[0-9]+\.[0-9]+|$LINE ${{ inputs.vault-version }}|g" \
            $(git ls-files README.md '**/README.md')

      - name: Commit and push changes
        run: |
          # TODO: commit and push changes           
          git status

  build-test-publish:
    needs:
      - update-readme
    if: always() && (needs.update-readme.result == 'success' || needs.update-readme.result == 'skipped')
    name: "@piiano/${{ matrix.package }}"
    uses: ./.github/workflows/build-test-publish-package.yml
    strategy:
      matrix:
        package:
          - testcontainers-vault
          - vault-client
          - typeorm-encryption
      # we need to run jobs sequentially because of the way packages depend on each other
      max-parallel: 1
      fail-fast: true
    with:
      path: ./sdk/${{ matrix.package }}
      bump: >-
        ${{ 
          github.event_name == 'push' &&
          'none' ||
          inputs[format('bump-{0}', matrix.package)]
        }}
    secrets: inherit
